出品機能(保存先パス)の修正
hew2023fgroup/HEW2023_Fgroup pull request #51
Opened 2023-12-08 06:26 UTC by syxnji

static/images/sell → HEW/site/static/images/sell

2023-12-08 06:57 UTC, BASARA0826 requested changes
2ファイル同時に送信したら画像が表示されませんでした。
あと、2画像とも一覧表示に出てきていたのでhtmlで制御できてないかも
![スクリーンショット 2023-12-08 155525](https://github.com/hew2023fgroup/HEW2023_Fgroup/assets/144750622/631c637b-509e-4fe3-942f-fb4dc60383ff)

2023-12-08 07:07 UTC, BASARA0826 commented
ついでにいうとダミーデータをHEW/siteから始まる相対パスに変更したらダミーデータの画像も消えちゃった☻

2023-12-08 18:33 UTC, syxnji commented
取り敢えず出品機能と簡易商品表示は修正した。
原因はvscodeで実行するとカレントディレクトリがスクリプトがあるところにならないことがあるらしい...
コード最初の方でカレントディレクトリの固定を追加したからもうおかしくなることはないはず。
出品写真のサムネイル指定とかはやり方をもう少し検討する。

2023-12-09 00:27 UTC, BASARA0826 commented
サムネイル指定できてからでいいよー

2023-12-09 08:27 UTC, syxnji commented
更新しました

2023-12-09 08:50 UTC, syxnji commented
sql修正しました。
あと、マイページの売り上げ計算と所持金チャージ機能 つけた。
商品購入すると所持金からお金減るようになった→足りない場合エラー処理

2023-12-09 09:29 UTC, BASARA0826 approved these changes
よく頑張りました！エラーなし！

2023-12-09 09:29 UTC, merged